In [19]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [20]:
iris = load_iris()

In [21]:
x = iris.data
y = iris.target

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.5)

In [23]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


1.0

In [24]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9866666666666667

In [25]:
rf = RandomForestClassifier(n_estimators=10)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9866666666666667

In [26]:
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
dt.score(x_test,y_test)

0.9733333333333334

In [29]:
def get_score(model,x_train,x_test,y_train,y_test):
  model.fit(x_train,y_train)
  return model.score(x_test,y_test)

In [30]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9866666666666667

In [31]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9866666666666667

In [32]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


1.0

In [33]:
get_score(DecisionTreeClassifier(),x_train,x_test,y_train,y_test)

0.9733333333333334

In [34]:
from sklearn.model_selection import cross_val_score

In [35]:
cross_val_score(LogisticRegression(),iris.data,iris.target,cv=3)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0.98, 0.96, 0.98])

In [36]:
cross_val_score(SVC(),iris.data,iris.target,cv=3)

array([0.96, 0.98, 0.94])

In [37]:
cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=3)

array([0.98, 0.94, 0.98])

In [38]:
cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3)

array([0.98, 0.94, 1.  ])